### ISSUE TITLE
dd isn't necessarily benchmarking the disk speed

### ISSUE THREAD

**Issue by FSMaxB** [psteinb/meetingcpp2017#1]
The command `dd if=/dev/zero of=/tmp/just_zeros bs=1G count=2` might just be testing the speed of your RAM because it doesn't flush the disk cache.

I experienced this before when I copied installer images to USB flash drives. Sometimes it takes just under a second to copy the entire image, but on unmount it takes >5 Minutes to flush the cache to the drive.

There are `dsync` and `fsync` and `nocache` options for `dd`, but I don't really know how to use them.

But I at least wanted to make you aware of the fact that this is not a good benchmark.

**Comment by psteinb** [comment]
thank you for the comment.

the meaning of this slide was mostly to illustrate the case for simple tools to get to know the behavior of the system. the word benchmark is used here in an ambivalent manner, I agree. I also agree that using `dd` does not reveal true system performance. In any case, if I have an application where the developer claims it is I/O bound and I want to know what the I/O for a given file on a system is, then `dd` is a valid choice AFAIK. On top, even if dd accepts additional flags to control the type of I/O performed (which potentially do not show cache effects), applications using `fread` and derivative commands from `libc` or `libstdc++` are likely to expose similar I/O bandwidths than a `dd` without flags.

Does that make sense?

**Comment by FSMaxB** [comment]
Makes sense. Since applications also benefit from the disk cache.

**Comment by FSMaxB** [comment]
Although it really depends on the access patterns. But then you can use special purpose disk benchmarking tools.

**Comment by psteinb** [comment]
exactly. thanks for posting.
